// Offline support for the Riyadh Metro map (generated by tools/build.py; edit tools/sw.template.js)
// Pages: network first, so updates show up at once; the last copy is used when there is no connection.
// Fonts, the QR library and icons: cached on first use. The visit counter is never cached.
const CACHE = "riyadhmetro-bade8d56e6";
const CORE = ["./", "index.html", "manifest.webmanifest", "icon-192.png", "apple-touch-icon.png"];

self.addEventListener("install", e => {
  e.waitUntil(caches.open(CACHE).then(c => c.addAll(CORE)).then(() => self.skipWaiting()));
});
self.addEventListener("activate", e => {
  e.waitUntil(caches.keys()
    .then(keys => Promise.all(keys.filter(k => k.startsWith("riyadhmetro-") && k !== CACHE).map(k => caches.delete(k))))
    .then(() => self.clients.claim()));
});
// the page tells us which language page it is, so that page also works offline
self.addEventListener("message", e => {
  if (e.data && e.data.type === "cache" && e.data.url) caches.open(CACHE).then(c => c.add(e.data.url)).catch(() => {});
});
self.addEventListener("fetch", e => {
  const req = e.request, url = new URL(req.url);
  if (req.method !== "GET" || url.hostname.endsWith("goatcounter.com") || url.hostname === "gc.zgo.at") return;
  if (req.mode === "navigate") {
    e.respondWith(fetch(req).then(res => {
      const copy = res.clone(); caches.open(CACHE).then(c => c.put(req, copy)); return res;
    }).catch(() => caches.match(req, { ignoreSearch: true }).then(r => r || caches.match("./"))));
    return;
  }
  const cacheable = url.origin === location.origin || /fonts\.(googleapis|gstatic)\.com$|cdnjs\.cloudflare\.com$/.test(url.hostname);
  if (!cacheable) return;
  e.respondWith(caches.match(req).then(hit => hit || fetch(req).then(res => {
    if (res.ok || res.type === "opaque") { const copy = res.clone(); caches.open(CACHE).then(c => c.put(req, copy)); }
    return res;
  })));
});
