# Texts for the language pages of the public site. Station names stay in English, as on the map.
# Placeholders: {std} {first} fares in SAR; {wk} {fri} opening hours; line texts get {a} {b} (termini).
TX = {
"en": dict(
 file="index.html", locale="en_US", dir="ltr",
 title="Interactive Riyadh Metro Map: all 6 lines",
 desc="Free, unofficial interactive map of the six Riyadh Metro lines. Tap two stations to see the travel time, fare and changes. Also a route planner from the airport, KAFD, Kingdom Centre, Al Batha or the National Museum, in Arabic, English, Urdu, Hindi, Bengali, Filipino, Russian and French.",
 ogTitle="Interactive Riyadh Metro Map",
 ogDesc="Tap two stations: travel time, fare and changes. All six lines. Free, in 8 languages.",
 h1="Interactive Riyadh Metro map",
 intro="An unofficial, free interactive map of the six Riyadh Metro lines. Tap a station, then another one, and the map shows the trip: travel time, stops, every change and the fare; you can also type a place or a station. It works in Arabic, English, Urdu, Hindi, Bengali, Filipino, Russian and French, on phones and computers, with nothing to install, and the location button finds the station nearest to you.",
 popular="Popular trips",
 trips=["Airport (Terminals 1-2) to KAFD", "Airport to Kingdom Centre", "Airport to Al Batha", "KAFD to the National Museum", "Kingdom Centre to Souq Al Zal", "Riyadh Railway Station to the National Museum"],
 lines="Lines and stations", line="<b>{n}:</b> {a} to {b}.",
 shared="The Yellow and Purple lines share the four stations from KAFD to SABIC.",
 faq="Questions",
 q=[("What are the Riyadh Metro opening hours?", "Saturday to Thursday {wk}, Friday {fri}. Hours change during Ramadan and on holidays; late in the evening the last train in your direction may leave before closing."),
    ("How much does the Riyadh Metro cost?", "One 2-hour ticket costs SAR {std} in standard class and SAR {first} in first class, with any number of rides and transfers on the metro and buses. There are also 3-day, 7-day and 30-day passes."),
    ("Can I take the metro from the airport?", "Yes. The Yellow Line serves Terminals 1-2, 3-4 and 5 and runs to KAFD, where it meets the Blue and Purple lines."),
    ("Is this the official map?", "No. This is an independent, non-commercial project, not affiliated with the Riyadh Public Transport authority. Travel times are estimates; always follow the signs and announcements at the station.")],
 report="Report a problem or suggest an improvement", close="Close", langName="English",
 guides="Guides to stations and places"),

"ar": dict(
 file="ar.html", locale="ar_SA", dir="rtl",
 title="خريطة مترو الرياض التفاعلية: المسارات الستة",
 desc="خريطة تفاعلية مجانية غير رسمية لمسارات مترو الرياض الستة. اضغط على محطتين لترى وقت الرحلة والسعر والتحويلات. وفيها أيضاً مخطط رحلات من المطار والمركز المالي وبرج المملكة والبطحاء والمتحف الوطني، بثماني لغات.",
 ogTitle="خريطة مترو الرياض التفاعلية",
 ogDesc="اضغط على محطتين: وقت الرحلة والسعر والتحويلات. المسارات الستة. مجاناً وبثماني لغات.",
 h1="خريطة مترو الرياض التفاعلية",
 intro="خريطة تفاعلية مجانية غير رسمية لمسارات مترو الرياض الستة. اضغط على محطة ثم على محطة أخرى، فتعرض الخريطة الرحلة: وقتها وعدد المحطات وكل تحويل والسعر، ويمكنك أيضاً كتابة اسم مكان أو محطة. تعمل بالعربية والإنجليزية والأردية والهندية والبنغالية والفلبينية والروسية والفرنسية على الهاتف والحاسوب دون تثبيت، وزر الموقع يجد أقرب محطة إليك.",
 popular="رحلات شائعة",
 trips=["المطار (الصالتان 1 و2) إلى المركز المالي", "المطار إلى برج المملكة", "المطار إلى البطحاء", "المركز المالي إلى المتحف الوطني", "برج المملكة إلى سوق الزل", "محطة قطار الرياض إلى المتحف الوطني"],
 lines="المسارات والمحطات", line="<b>{n}:</b> من {a} إلى {b}.",
 shared="يشترك المساران الأصفر والبنفسجي في المحطات الأربع من المركز المالي إلى سابك.",
 faq="أسئلة",
 q=[("ما مواعيد تشغيل مترو الرياض؟", "من السبت إلى الخميس {wk}، والجمعة {fri}. تتغير المواعيد في رمضان والأعياد؛ في وقت متأخر قد يغادر آخر قطار في اتجاهك قبل الإغلاق."),
    ("كم سعر تذكرة مترو الرياض؟", "تذكرة الساعتين بسعر {std} ريال للدرجة العادية و{first} ريال للدرجة الأولى، مع عدد غير محدود من الرحلات والتحويلات في المترو والحافلات. وتتوفر تذاكر 3 أيام و7 أيام و30 يوماً."),
    ("هل يمكن الوصول من المطار بالمترو؟", "نعم. المسار الأصفر يخدم الصالات من 1 إلى 5 ويصل إلى المركز المالي حيث يلتقي بالمسارين الأزرق والبنفسجي."),
    ("هل هذه الخريطة الرسمية؟", "لا. هذا مشروع مستقل غير تجاري ولا علاقة له بالهيئة الملكية لمدينة الرياض أو النقل العام. الأوقات تقديرية؛ اتبع دائماً اللوحات والإعلانات في المحطة.")],
 report="الإبلاغ عن مشكلة أو اقتراح تحسين", close="إغلاق", langName="العربية",
 guides="أدلة المحطات والأماكن"),

"ur": dict(
 file="ur.html", locale="ur_PK", dir="rtl",
 title="ریاض میٹرو کا انٹرایکٹو نقشہ: تمام 6 لائنیں",
 desc="ریاض میٹرو کی چھ لائنوں کا مفت، غیر سرکاری انٹرایکٹو نقشہ۔ دو اسٹیشنوں پر ٹیپ کریں اور سفر کا وقت، کرایہ اور تبدیلیاں دیکھیں۔ ایئرپورٹ، KAFD، کنگڈم سینٹر، البطحاء یا نیشنل میوزیم کے لیے روٹ پلانر بھی، آٹھ زبانوں میں۔",
 ogTitle="ریاض میٹرو کا انٹرایکٹو نقشہ",
 ogDesc="دو اسٹیشنوں پر ٹیپ کریں: سفر کا وقت، کرایہ اور تبدیلیاں۔ تمام چھ لائنیں۔ مفت، آٹھ زبانوں میں۔",
 h1="ریاض میٹرو کا انٹرایکٹو نقشہ",
 intro="ریاض میٹرو کی چھ لائنوں کا مفت، غیر سرکاری انٹرایکٹو نقشہ۔ ایک اسٹیشن پر ٹیپ کریں، پھر دوسرے پر، اور نقشہ پورا سفر دکھائے گا: سفر کا وقت، اسٹاپ، ہر تبدیلی اور کرایہ؛ آپ کوئی جگہ یا اسٹیشن لکھ بھی سکتے ہیں۔ یہ عربی، انگریزی، اردو، ہندی، بنگالی، فلپائنی، روسی اور فرانسیسی میں فون اور کمپیوٹر پر بغیر انسٹال کیے چلتا ہے، اور لوکیشن بٹن قریب ترین اسٹیشن ڈھونڈتا ہے۔",
 popular="مشہور سفر",
 trips=["ایئرپورٹ (ٹرمینل 1-2) سے KAFD", "ایئرپورٹ سے کنگڈم سینٹر", "ایئرپورٹ سے البطحاء", "KAFD سے نیشنل میوزیم", "کنگڈم سینٹر سے سوق الزل", "ریاض ریلوے اسٹیشن سے نیشنل میوزیم"],
 lines="لائنیں اور اسٹیشن", line="<b>{n}:</b> {a} سے {b} تک۔",
 shared="یلو اور پرپل لائن KAFD سے SABIC تک چار اسٹیشن مشترک استعمال کرتی ہیں۔",
 faq="سوالات",
 q=[("ریاض میٹرو کے اوقات کیا ہیں؟", "ہفتہ سے جمعرات {wk}، جمعہ {fri}۔ رمضان اور چھٹیوں میں اوقات بدلتے ہیں؛ رات دیر سے آپ کی سمت کی آخری ٹرین بند ہونے سے پہلے نکل سکتی ہے۔"),
    ("ریاض میٹرو کا کرایہ کتنا ہے؟", "2 گھنٹے کا ٹکٹ اسٹینڈرڈ کلاس میں SAR {std} اور فرسٹ کلاس میں SAR {first}، میٹرو اور بسوں میں جتنے چاہیں سفر اور ٹرانسفر۔ 3، 7 اور 30 دن کے پاس بھی ہیں۔"),
    ("کیا ایئرپورٹ سے میٹرو مل جاتی ہے؟", "جی ہاں۔ یلو لائن ٹرمینل 1-2، 3-4 اور 5 سے KAFD تک جاتی ہے، جہاں بلیو اور پرپل لائن سے ملتی ہے۔"),
    ("کیا یہ سرکاری نقشہ ہے؟", "نہیں۔ یہ ایک آزاد، غیر تجارتی منصوبہ ہے اور ریاض پبلک ٹرانسپورٹ سے منسلک نہیں۔ اوقات اندازاً ہیں؛ ہمیشہ اسٹیشن کے نشانات اور اعلانات کو دیکھیں۔")],
 report="مسئلہ بتائیں یا بہتری تجویز کریں", close="بند کریں", langName="اردو",
 guides="اسٹیشنوں اور جگہوں کی گائیڈ (انگریزی میں)"),

"hi": dict(
 file="hi.html", locale="hi_IN", dir="ltr",
 title="इंटरैक्टिव रियाद मेट्रो मैप: सभी 6 लाइनें",
 desc="रियाद मेट्रो की छह लाइनों का मुफ़्त, अनौपचारिक इंटरैक्टिव मैप। दो स्टेशनों पर टैप करें और यात्रा का समय, किराया और बदलाव देखें। एयरपोर्ट, KAFD, किंगडम सेंटर, अल बथा या नेशनल म्यूज़ियम के लिए रूट प्लानर भी, आठ भाषाओं में।",
 ogTitle="इंटरैक्टिव रियाद मेट्रो मैप",
 ogDesc="दो स्टेशनों पर टैप करें: यात्रा का समय, किराया और बदलाव। सभी छह लाइनें। मुफ़्त, आठ भाषाओं में।",
 h1="इंटरैक्टिव रियाद मेट्रो मैप",
 intro="रियाद मेट्रो की छह लाइनों का मुफ़्त, अनौपचारिक इंटरैक्टिव मैप। एक स्टेशन पर टैप करें, फिर दूसरे पर, और मैप पूरी यात्रा दिखाएगा: यात्रा का समय, स्टॉप, हर बदलाव और किराया; आप कोई जगह या स्टेशन लिख भी सकते हैं। यह अरबी, अंग्रेज़ी, उर्दू, हिंदी, बांग्ला, फ़िलिपिनो, रूसी और फ़्रेंच में फ़ोन और कंप्यूटर पर बिना इंस्टॉल किए चलता है, और लोकेशन बटन सबसे पास का स्टेशन ढूँढता है।",
 popular="लोकप्रिय यात्राएँ",
 trips=["एयरपोर्ट (टर्मिनल 1-2) से KAFD", "एयरपोर्ट से किंगडम सेंटर", "एयरपोर्ट से अल बथा", "KAFD से नेशनल म्यूज़ियम", "किंगडम सेंटर से सूक़ अल ज़ल", "रियाद रेलवे स्टेशन से नेशनल म्यूज़ियम"],
 lines="लाइनें और स्टेशन", line="<b>{n}:</b> {a} से {b} तक।",
 shared="येलो और पर्पल लाइन KAFD से SABIC तक चार स्टेशन साझा करती हैं।",
 faq="सवाल",
 q=[("रियाद मेट्रो का समय क्या है?", "शनिवार से गुरुवार {wk}, शुक्रवार {fri}। रमज़ान और छुट्टियों में समय बदलता है; देर रात आपकी दिशा की आख़िरी ट्रेन बंद होने से पहले निकल सकती है।"),
    ("रियाद मेट्रो का किराया कितना है?", "2 घंटे का टिकट स्टैंडर्ड क्लास में SAR {std} और फ़र्स्ट क्लास में SAR {first}, मेट्रो और बसों में जितनी चाहें यात्राएँ और ट्रांसफ़र। 3, 7 और 30 दिन के पास भी हैं।"),
    ("क्या एयरपोर्ट से मेट्रो मिलती है?", "हाँ। येलो लाइन टर्मिनल 1-2, 3-4 और 5 से KAFD तक जाती है, जहाँ ब्लू और पर्पल लाइन मिलती हैं।"),
    ("क्या यह आधिकारिक नक्शा है?", "नहीं। यह एक स्वतंत्र, गैर-व्यावसायिक प्रोजेक्ट है और रियाद पब्लिक ट्रांसपोर्ट से जुड़ा नहीं है। समय अनुमानित हैं; हमेशा स्टेशन के संकेत और घोषणाएँ देखें।")],
 report="समस्या बताएँ या सुधार सुझाएँ", close="बंद करें", langName="हिन्दी",
 guides="स्टेशनों और जगहों की गाइड (अंग्रेज़ी में)"),

"bn": dict(
 file="bn.html", locale="bn_BD", dir="ltr",
 title="রিয়াদ মেট্রোর ইন্টারঅ্যাক্টিভ মানচিত্র: সব ৬টি লাইন",
 desc="রিয়াদ মেট্রোর ছয়টি লাইনের বিনামূল্যের, অনানুষ্ঠানিক ইন্টারঅ্যাক্টিভ মানচিত্র। দুটি স্টেশনে চাপুন, দেখুন যাত্রার সময়, ভাড়া ও বদল। বিমানবন্দর, KAFD, কিংডম সেন্টার, আল বাথা বা জাতীয় জাদুঘরে যাওয়ার রুট প্ল্যানারও আছে, আট ভাষায়।",
 ogTitle="রিয়াদ মেট্রোর ইন্টারঅ্যাক্টিভ মানচিত্র",
 ogDesc="দুটি স্টেশনে চাপুন: যাত্রার সময়, ভাড়া ও বদল। সব ছয়টি লাইন। বিনামূল্যে, আট ভাষায়।",
 h1="রিয়াদ মেট্রোর ইন্টারঅ্যাক্টিভ মানচিত্র",
 intro="রিয়াদ মেট্রোর ছয়টি লাইনের বিনামূল্যের, অনানুষ্ঠানিক ইন্টারঅ্যাক্টিভ মানচিত্র। একটি স্টেশনে চাপুন, তারপর আরেকটিতে, মানচিত্র পুরো যাত্রা দেখাবে: যাত্রার সময়, স্টপ, প্রতিটি বদল ও ভাড়া; চাইলে কোনো জায়গা বা স্টেশনের নামও লিখতে পারেন। আরবি, ইংরেজি, উর্দু, হিন্দি, বাংলা, ফিলিপিনো, রুশ ও ফরাসি ভাষায় ফোন ও কম্পিউটারে কিছু ইনস্টল না করেই চলে, আর লোকেশন বোতাম কাছের স্টেশন খুঁজে দেয়।",
 popular="জনপ্রিয় যাত্রা",
 trips=["বিমানবন্দর (টার্মিনাল ১-২) থেকে KAFD", "বিমানবন্দর থেকে কিংডম সেন্টার", "বিমানবন্দর থেকে আল বাথা", "KAFD থেকে জাতীয় জাদুঘর", "কিংডম সেন্টার থেকে সুক আল জাল", "রিয়াদ রেলস্টেশন থেকে জাতীয় জাদুঘর"],
 lines="লাইন ও স্টেশন", line="<b>{n}:</b> {a} থেকে {b}।",
 shared="ইয়েলো ও পার্পল লাইন KAFD থেকে SABIC পর্যন্ত চারটি স্টেশন ভাগ করে।",
 faq="প্রশ্ন",
 q=[("রিয়াদ মেট্রো কখন চলে?", "শনিবার থেকে বৃহস্পতিবার {wk}, শুক্রবার {fri}। রমজান ও ছুটির দিনে সময় বদলায়; রাতে দেরিতে আপনার দিকের শেষ ট্রেন বন্ধ হওয়ার আগেই ছেড়ে যেতে পারে।"),
    ("রিয়াদ মেট্রোর ভাড়া কত?", "২ ঘণ্টার টিকিট স্ট্যান্ডার্ড ক্লাসে SAR {std} এবং ফার্স্ট ক্লাসে SAR {first}, মেট্রো ও বাসে যত খুশি যাত্রা ও ট্রান্সফার। ৩, ৭ ও ৩০ দিনের পাসও আছে।"),
    ("বিমানবন্দর থেকে কি মেট্রো পাওয়া যায়?", "হ্যাঁ। ইয়েলো লাইন টার্মিনাল ১-২, ৩-৪ ও ৫ থেকে KAFD পর্যন্ত যায়, যেখানে ব্লু ও পার্পল লাইনের সঙ্গে মেলে।"),
    ("এটা কি সরকারি মানচিত্র?", "না। এটি একটি স্বাধীন, অবাণিজ্যিক প্রকল্প, রিয়াদ পাবলিক ট্রান্সপোর্টের সঙ্গে যুক্ত নয়। সময়গুলো আনুমানিক; সবসময় স্টেশনের চিহ্ন ও ঘোষণা মেনে চলুন।")],
 report="সমস্যা জানান বা উন্নতির পরামর্শ দিন", close="বন্ধ করুন", langName="বাংলা",
 guides="স্টেশন ও জায়গার গাইড (ইংরেজিতে)"),

"tl": dict(
 file="tl.html", locale="fil_PH", dir="ltr",
 title="Interactive na Mapa ng Riyadh Metro: lahat ng 6 na linya",
 desc="Libre at hindi opisyal na interactive na mapa ng anim na linya ng Riyadh Metro. Pindutin ang dalawang istasyon para makita ang oras ng biyahe, pamasahe at mga lipat. May route planner din mula sa airport, KAFD, Kingdom Centre, Al Batha o National Museum, sa walong wika.",
 ogTitle="Interactive na Mapa ng Riyadh Metro",
 ogDesc="Pindutin ang dalawang istasyon: oras ng biyahe, pamasahe at mga lipat. Lahat ng anim na linya. Libre, sa walong wika.",
 h1="Interactive na mapa ng Riyadh Metro",
 intro="Libre at hindi opisyal na interactive na mapa ng anim na linya ng Riyadh Metro. Pindutin ang isang istasyon, pagkatapos ang isa pa, at ipapakita ng mapa ang biyahe: oras, mga hintuan, bawat lipat at pamasahe; puwede ka ring mag-type ng lugar o istasyon. Gumagana ito sa Arabic, English, Urdu, Hindi, Bengali, Filipino, Russian at French sa phone at computer nang walang ini-install, at hinahanap ng location button ang pinakamalapit na istasyon.",
 popular="Mga sikat na biyahe",
 trips=["Airport (Terminal 1-2) papuntang KAFD", "Airport papuntang Kingdom Centre", "Airport papuntang Al Batha", "KAFD papuntang National Museum", "Kingdom Centre papuntang Souq Al Zal", "Riyadh Railway Station papuntang National Museum"],
 lines="Mga linya at istasyon", line="<b>{n}:</b> {a} hanggang {b}.",
 shared="Magkasama ang Yellow at Purple Line sa apat na istasyon mula KAFD hanggang SABIC.",
 faq="Mga tanong",
 q=[("Anong oras bukas ang Riyadh Metro?", "Sabado hanggang Huwebes {wk}, Biyernes {fri}. Nagbabago ang oras tuwing Ramadan at holiday; kapag gabi na, puwedeng umalis ang huling tren sa direksyon mo bago magsara."),
    ("Magkano ang pamasahe sa Riyadh Metro?", "Ang 2-oras na tiket ay SAR {std} sa standard class at SAR {first} sa first class, walang limitasyong sakay at lipat sa metro at bus. May 3-araw, 7-araw at 30-araw na pass din."),
    ("May metro ba mula sa airport?", "Oo. Dumadaan ang Yellow Line sa Terminal 1-2, 3-4 at 5 at papunta sa KAFD, kung saan nagtatagpo ito sa Blue at Purple Line."),
    ("Opisyal ba ang mapang ito?", "Hindi. Isa itong independiyente at hindi pangkomersyong proyekto, walang kaugnayan sa Riyadh Public Transport. Tantiya lang ang mga oras; laging sundin ang karatula at anunsyo sa istasyon.")],
 report="Mag-ulat ng problema o magmungkahi", close="Isara", langName="Filipino",
 guides="Gabay sa mga istasyon at lugar (sa English)"),
"ru": dict(
 file="ru.html", locale="ru_RU", dir="ltr",
 title="Интерактивная схема метро Эр-Рияда: все 6 линий",
 desc="Бесплатная неофициальная интерактивная схема шести линий метро Эр-Рияда. Нажмите на две станции и увидите время в пути, цену билета и пересадки. Есть и построение маршрута из аэропорта до KAFD, Kingdom Centre, Аль-Батхи или Национального музея, на 8 языках.",
 ogTitle="Интерактивная схема метро Эр-Рияда",
 ogDesc="Нажмите на две станции: время в пути, цена билета и пересадки. Все шесть линий. Бесплатно, на 8 языках.",
 h1="Интерактивная схема метро Эр-Рияда",
 intro="Неофициальная бесплатная интерактивная схема шести линий метро Эр-Рияда. Нажмите на одну станцию, потом на другую, и схема покажет поездку: время в пути, остановки, все пересадки и цену билета; можно и ввести место или станцию. Сайт работает на арабском, английском, урду, хинди, бенгальском, филиппинском, русском и французском, на телефоне и компьютере, ничего устанавливать не нужно, а кнопка геолокации найдёт ближайшую к вам станцию.",
 popular="Популярные поездки",
 trips=["Аэропорт (терминалы 1-2) → KAFD", "Аэропорт → Kingdom Centre", "Аэропорт → Аль-Батха", "KAFD → Национальный музей", "Kingdom Centre → Souq Al Zal", "Железнодорожный вокзал Эр-Рияда → Национальный музей"],
 lines="Линии и станции", line="<b>{n}:</b> от {a} до {b}.",
 shared="Жёлтая и фиолетовая линии проходят вместе через четыре станции от KAFD до SABIC.",
 faq="Вопросы",
 q=[("Когда работает метро Эр-Рияда?", "С субботы по четверг {wk}, в пятницу {fri}. В Рамадан и праздники часы меняются; поздно вечером последний поезд в вашем направлении может уйти раньше закрытия."),
    ("Сколько стоит проезд в метро Эр-Рияда?", "Билет на 2 часа стоит {std} SAR в стандартном классе и {first} SAR в первом, на любое число поездок и пересадок в метро и автобусах. Есть также проездные на 3, 7 и 30 дней."),
    ("Можно ли доехать на метро из аэропорта?", "Да. Жёлтая линия обслуживает терминалы 1-2, 3-4 и 5 и идёт до KAFD, где пересекается с синей и фиолетовой линиями."),
    ("Это официальная схема?", "Нет. Это независимый некоммерческий проект, не связанный с транспортными властями Эр-Рияда. Время в пути примерное; на станции всегда ориентируйтесь на указатели и объявления.")],
 report="Сообщить о проблеме или предложить улучшение", close="Закрыть", langName="Русский",
 guides="Гиды по станциям и местам (на английском)"),

"fr": dict(
 file="fr.html", locale="fr_FR", dir="ltr",
 title="Plan interactif du métro de Riyad : les 6 lignes",
 desc="Plan interactif gratuit et non officiel des six lignes du métro de Riyad. Touchez deux stations pour voir le temps de trajet, le prix du billet et les correspondances. Calcul d’itinéraire depuis l’aéroport, KAFD, le Kingdom Centre, Al Batha ou le Musée national, en 8 langues.",
 ogTitle="Plan interactif du métro de Riyad",
 ogDesc="Touchez deux stations : temps de trajet, prix du billet et correspondances. Les six lignes. Gratuit, en 8 langues.",
 h1="Plan interactif du métro de Riyad",
 intro="Un plan interactif gratuit et non officiel des six lignes du métro de Riyad. Touchez une station, puis une autre : le plan affiche le trajet avec le temps de parcours, les arrêts, chaque correspondance et le prix du billet ; vous pouvez aussi saisir un lieu ou une station. Il fonctionne en arabe, anglais, ourdou, hindi, bengali, filipino, russe et français, sur téléphone et ordinateur, sans rien installer, et le bouton de localisation trouve la station la plus proche.",
 popular="Trajets populaires",
 trips=["Aéroport (terminaux 1-2) → KAFD", "Aéroport → Kingdom Centre", "Aéroport → Al Batha", "KAFD → Musée national", "Kingdom Centre → Souq Al Zal", "Gare de Riyad → Musée national"],
 lines="Lignes et stations", line="<b>{n} :</b> de {a} à {b}.",
 shared="Les lignes jaune et violette partagent les quatre stations de KAFD à SABIC.",
 faq="Questions",
 q=[("Quels sont les horaires du métro de Riyad ?", "Du samedi au jeudi {wk}, le vendredi {fri}. Les horaires changent pendant le Ramadan et les jours fériés ; tard le soir, le dernier train dans votre sens peut partir avant la fermeture."),
    ("Combien coûte le métro de Riyad ?", "Un billet de 2 heures coûte {std} SAR en classe standard et {first} SAR en première classe, pour autant de trajets et de correspondances que vous voulez dans le métro et les bus. Il existe aussi des forfaits 3, 7 et 30 jours."),
    ("Peut-on prendre le métro depuis l’aéroport ?", "Oui. La ligne jaune dessert les terminaux 1-2, 3-4 et 5 et va jusqu’à KAFD, où elle croise les lignes bleue et violette."),
    ("Est-ce le plan officiel ?", "Non. C’est un projet indépendant et non commercial, sans lien avec les autorités des transports de Riyad. Les temps sont estimés ; suivez toujours la signalisation et les annonces en station.")],
 report="Signaler un problème ou proposer une amélioration", close="Fermer", langName="Français",
 guides="Guides des stations et des lieux (en anglais)"),
}
ORDER = ["en", "ar", "ur", "hi", "bn", "tl", "ru", "fr"]
