# Texts for the language pages of the public site. Station names stay in English, as on the map.
# Placeholders: {std} {first} fares in SAR; {wk} {fri} opening hours; line texts get {a} {b} (termini).
TX = {
"en": dict(
 file="index.html", locale="en_US", dir="ltr",
 title="Riyadh Metro Map &amp; Route Planner: all 6 lines",
 desc="Free, unofficial Riyadh Metro map and journey planner. Get from the airport, KAFD, Kingdom Centre, Al Batha or the National Museum with step-by-step directions, travel times, fares and opening hours, in Arabic, English, Urdu, Hindi, Bengali, Filipino, Russian and French.",
 ogTitle="Riyadh Metro Map &amp; Route Planner",
 ogDesc="All six lines: directions, travel times, fares and opening hours. Free, in 8 languages.",
 h1="Riyadh Metro map and route planner",
 intro="An unofficial, free map of the six Riyadh Metro lines. Type a place or a station, or tap a station on the map, and the planner shows the route with every change, an estimated travel time and the fare. It works in Arabic, English, Urdu, Hindi, Bengali, Filipino, Russian and French, on phones and computers, with nothing to install, and the location button finds the station nearest to you.",
 popular="Popular trips",
 trips=["Airport (Terminals 1-2) to KAFD", "Airport to Kingdom Centre", "Airport to Al Batha", "KAFD to the National Museum", "Kingdom Centre to Souq Al Zal", "Riyadh Railway Station to the National Museum"],
 lines="Lines and stations", line="<b>{n}:</b> {a} to {b}.",
 shared="The Yellow and Purple lines share the four stations from KAFD to SABIC.",
 faq="Questions",
 q=[("What are the Riyadh Metro opening hours?", "Saturday to Thursday {wk}, Friday {fri}. Hours change during Ramadan and on holidays; late in the evening the last train in your direction may leave before closing."),
    ("How much does the Riyadh Metro cost?", "One 2-hour ticket costs SAR {std} in standard class and SAR {first} in first class, with any number of rides and transfers on the metro and buses. There are also 3-day, 7-day and 30-day passes."),
    ("Can I take the metro from the airport?", "Yes. The Yellow Line serves Terminals 1-2, 3-4 and 5 and runs to KAFD, where it meets the Blue and Purple lines."),
    ("Is this the official map?", "No. This is an independent, non-commercial project, not affiliated with the Riyadh Public Transport authority. Travel times are estimates; always follow the signs and announcements at the station.")],
 report="Report a problem or suggest an improvement", close="Close", langName="English",
 guides="Guides to stations and places"),

"ar": dict(
 file="ar.html", locale="ar_SA", dir="rtl",
 title="خريطة مترو الرياض ومخطط الرحلات: المسارات الستة",
 desc="خريطة مجانية غير رسمية لمترو الرياض ومخطط رحلات. تنقّل من المطار والمركز المالي وبرج المملكة والبطحاء والمتحف الوطني مع خطوات واضحة ووقت الرحلة والسعر ومواعيد التشغيل، بثماني لغات.",
 ogTitle="خريطة مترو الرياض ومخطط الرحلات",
 ogDesc="المسارات الستة: الاتجاهات ووقت الرحلة والسعر ومواعيد التشغيل. مجاناً وبثماني لغات.",
 h1="خريطة مترو الرياض ومخطط الرحلات",
 intro="خريطة مجانية غير رسمية لمسارات مترو الرياض الستة. اكتب اسم مكان أو محطة، أو اضغط على محطة في الخريطة، فيعرض المخطط الطريق مع كل تحويل ووقت الرحلة التقديري والسعر. تعمل بالعربية والإنجليزية والأردية والهندية والبنغالية والفلبينية والروسية والفرنسية على الهاتف والحاسوب دون تثبيت، وزر الموقع يجد أقرب محطة إليك.",
 popular="رحلات شائعة",
 trips=["المطار (الصالات 1-2) إلى المركز المالي", "المطار إلى برج المملكة", "المطار إلى البطحاء", "المركز المالي إلى المتحف الوطني", "برج المملكة إلى سوق الزل", "محطة قطار الرياض إلى المتحف الوطني"],
 lines="المسارات والمحطات", line="<b>{n}:</b> من {a} إلى {b}.",
 shared="يشترك المساران الأصفر والبنفسجي في المحطات الأربع من المركز المالي إلى سابك.",
 faq="أسئلة",
 q=[("ما مواعيد تشغيل مترو الرياض؟", "من السبت إلى الخميس {wk}، والجمعة {fri}. تتغير المواعيد في رمضان والأعياد؛ في وقت متأخر قد يغادر آخر قطار في اتجاهك قبل الإغلاق."),
    ("كم سعر تذكرة مترو الرياض؟", "تذكرة الساعتين بسعر {std} ريال للدرجة العادية و{first} ريال للدرجة الأولى، مع عدد غير محدود من الرحلات والتحويلات في المترو والحافلات. وتتوفر تذاكر 3 أيام و7 أيام و30 يوماً."),
    ("هل يمكن الوصول من المطار بالمترو؟", "نعم. المسار الأصفر يخدم الصالات 1-2 و3-4 و5 ويصل إلى المركز المالي حيث يلتقي بالمسارين الأزرق والبنفسجي."),
    ("هل هذه الخريطة الرسمية؟", "لا. هذا مشروع مستقل غير تجاري ولا علاقة له بالهيئة الملكية لمدينة الرياض أو النقل العام. الأوقات تقديرية؛ اتبع دائماً اللوحات والإعلانات في المحطة.")],
 report="الإبلاغ عن مشكلة أو اقتراح تحسين", close="إغلاق", langName="العربية",
 guides="أدلة المحطات والأماكن"),

"ur": dict(
 file="ur.html", locale="ur_PK", dir="rtl",
 title="ریاض میٹرو کا نقشہ اور روٹ پلانر: تمام 6 لائنیں",
 desc="ریاض میٹرو کا مفت، غیر سرکاری نقشہ اور سفر پلانر۔ ایئرپورٹ، KAFD، کنگڈم سینٹر، البطحاء یا نیشنل میوزیم تک قدم بہ قدم راستہ، سفر کا وقت، کرایہ اور اوقات، آٹھ زبانوں میں۔",
 ogTitle="ریاض میٹرو کا نقشہ اور روٹ پلانر",
 ogDesc="تمام چھ لائنیں: راستہ، سفر کا وقت، کرایہ اور اوقات۔ مفت، آٹھ زبانوں میں۔",
 h1="ریاض میٹرو کا نقشہ اور روٹ پلانر",
 intro="ریاض میٹرو کی چھ لائنوں کا مفت، غیر سرکاری نقشہ۔ کسی جگہ یا اسٹیشن کا نام لکھیں یا نقشے پر اسٹیشن ٹیپ کریں، پلانر ہر تبدیلی، اندازاً وقت اور کرایے کے ساتھ راستہ دکھاتا ہے۔ یہ عربی، انگریزی، اردو، ہندی، بنگالی، فلپائنی، روسی اور فرانسیسی میں فون اور کمپیوٹر پر بغیر انسٹال کیے چلتا ہے، اور لوکیشن بٹن قریب ترین اسٹیشن ڈھونڈتا ہے۔",
 popular="مشہور سفر",
 trips=["ایئرپورٹ (ٹرمینل 1-2) سے KAFD", "ایئرپورٹ سے کنگڈم سینٹر", "ایئرپورٹ سے البطحاء", "KAFD سے نیشنل میوزیم", "کنگڈم سینٹر سے سوق الزل", "ریاض ریلوے اسٹیشن سے نیشنل میوزیم"],
 lines="لائنیں اور اسٹیشن", line="<b>{n}:</b> {a} سے {b} تک۔",
 shared="یلو اور پرپل لائن KAFD سے SABIC تک چار اسٹیشن مشترک استعمال کرتی ہیں۔",
 faq="سوالات",
 q=[("ریاض میٹرو کے اوقات کیا ہیں؟", "ہفتہ سے جمعرات {wk}، جمعہ {fri}۔ رمضان اور چھٹیوں میں اوقات بدلتے ہیں؛ رات دیر سے آپ کی سمت کی آخری ٹرین بند ہونے سے پہلے نکل سکتی ہے۔"),
    ("ریاض میٹرو کا کرایہ کتنا ہے؟", "2 گھنٹے کا ٹکٹ اسٹینڈرڈ کلاس میں SAR {std} اور فرسٹ کلاس میں SAR {first}، میٹرو اور بسوں میں جتنے چاہیں سفر اور ٹرانسفر۔ 3، 7 اور 30 دن کے پاس بھی ہیں۔"),
    ("کیا ایئرپورٹ سے میٹرو مل جاتی ہے؟", "جی ہاں۔ یلو لائن ٹرمینل 1-2، 3-4 اور 5 سے KAFD تک جاتی ہے، جہاں بلیو اور پرپل لائن سے ملتی ہے۔"),
    ("کیا یہ سرکاری نقشہ ہے؟", "نہیں۔ یہ ایک آزاد، غیر تجارتی منصوبہ ہے اور ریاض پبلک ٹرانسپورٹ سے منسلک نہیں۔ اوقات اندازاً ہیں؛ ہمیشہ اسٹیشن کے نشانات اور اعلانات کو دیکھیں۔")],
 report="مسئلہ بتائیں یا بہتری تجویز کریں", close="بند کریں", langName="اردو",
 guides="اسٹیشنوں اور جگہوں کی گائیڈ (انگریزی میں)"),

"hi": dict(
 file="hi.html", locale="hi_IN", dir="ltr",
 title="रियाद मेट्रो मैप और रूट प्लानर: सभी 6 लाइनें",
 desc="मुफ़्त, अनौपचारिक रियाद मेट्रो मैप और यात्रा प्लानर। एयरपोर्ट, KAFD, किंगडम सेंटर, अल बथा या नेशनल म्यूज़ियम तक चरण-दर-चरण रास्ता, यात्रा समय, किराया और समय, आठ भाषाओं में।",
 ogTitle="रियाद मेट्रो मैप और रूट प्लानर",
 ogDesc="सभी छह लाइनें: रास्ता, यात्रा समय, किराया और संचालन समय। मुफ़्त, आठ भाषाओं में।",
 h1="रियाद मेट्रो मैप और रूट प्लानर",
 intro="रियाद मेट्रो की छह लाइनों का मुफ़्त, अनौपचारिक नक्शा। कोई जगह या स्टेशन लिखें या नक्शे पर स्टेशन टैप करें, प्लानर हर बदलाव, अनुमानित समय और किराए के साथ रास्ता दिखाता है। यह अरबी, अंग्रेज़ी, उर्दू, हिंदी, बांग्ला, फ़िलिपिनो, रूसी और फ़्रेंच में फ़ोन और कंप्यूटर पर बिना इंस्टॉल किए चलता है, और लोकेशन बटन सबसे पास का स्टेशन ढूँढता है।",
 popular="लोकप्रिय यात्राएँ",
 trips=["एयरपोर्ट (टर्मिनल 1-2) से KAFD", "एयरपोर्ट से किंगडम सेंटर", "एयरपोर्ट से अल बथा", "KAFD से नेशनल म्यूज़ियम", "किंगडम सेंटर से सूक़ अल ज़ल", "रियाद रेलवे स्टेशन से नेशनल म्यूज़ियम"],
 lines="लाइनें और स्टेशन", line="<b>{n}:</b> {a} से {b} तक।",
 shared="येलो और पर्पल लाइन KAFD से SABIC तक चार स्टेशन साझा करती हैं।",
 faq="सवाल",
 q=[("रियाद मेट्रो का समय क्या है?", "शनिवार से गुरुवार {wk}, शुक्रवार {fri}। रमज़ान और छुट्टियों में समय बदलता है; देर रात आपकी दिशा की आख़िरी ट्रेन बंद होने से पहले निकल सकती है।"),
    ("रियाद मेट्रो का किराया कितना है?", "2 घंटे का टिकट स्टैंडर्ड क्लास में SAR {std} और फ़र्स्ट क्लास में SAR {first}, मेट्रो और बसों में जितनी चाहें यात्राएँ और ट्रांसफ़र। 3, 7 और 30 दिन के पास भी हैं।"),
    ("क्या एयरपोर्ट से मेट्रो मिलती है?", "हाँ। येलो लाइन टर्मिनल 1-2, 3-4 और 5 से KAFD तक जाती है, जहाँ ब्लू और पर्पल लाइन मिलती हैं।"),
    ("क्या यह आधिकारिक नक्शा है?", "नहीं। यह एक स्वतंत्र, गैर-व्यावसायिक प्रोजेक्ट है और रियाद पब्लिक ट्रांसपोर्ट से जुड़ा नहीं है। समय अनुमानित हैं; हमेशा स्टेशन के संकेत और घोषणाएँ देखें।")],
 report="समस्या बताएँ या सुधार सुझाएँ", close="बंद करें", langName="हिन्दी",
 guides="स्टेशनों और जगहों की गाइड (अंग्रेज़ी में)"),

"bn": dict(
 file="bn.html", locale="bn_BD", dir="ltr",
 title="রিয়াদ মেট্রো মানচিত্র ও রুট প্ল্যানার: সব ৬টি লাইন",
 desc="বিনামূল্যে, অনানুষ্ঠানিক রিয়াদ মেট্রো মানচিত্র ও যাত্রা পরিকল্পক। বিমানবন্দর, KAFD, কিংডম সেন্টার, আল বাথা বা জাতীয় জাদুঘরে যাওয়ার ধাপে ধাপে পথ, যাত্রার সময়, ভাড়া ও চলাচলের সময়, আট ভাষায়।",
 ogTitle="রিয়াদ মেট্রো মানচিত্র ও রুট প্ল্যানার",
 ogDesc="সব ছয়টি লাইন: পথ, যাত্রার সময়, ভাড়া ও চলাচলের সময়। বিনামূল্যে, আট ভাষায়।",
 h1="রিয়াদ মেট্রো মানচিত্র ও রুট প্ল্যানার",
 intro="রিয়াদ মেট্রোর ছয়টি লাইনের বিনামূল্যের, অনানুষ্ঠানিক মানচিত্র। কোনো জায়গা বা স্টেশনের নাম লিখুন বা মানচিত্রে একটি স্টেশনে চাপুন, প্ল্যানার প্রতিটি বদল, আনুমানিক সময় ও ভাড়াসহ পথ দেখায়। আরবি, ইংরেজি, উর্দু, হিন্দি, বাংলা, ফিলিপিনো, রুশ ও ফরাসি ভাষায় ফোন ও কম্পিউটারে কিছু ইনস্টল না করেই চলে, আর লোকেশন বোতাম কাছের স্টেশন খুঁজে দেয়।",
 popular="জনপ্রিয় যাত্রা",
 trips=["বিমানবন্দর (টার্মিনাল ১-২) থেকে KAFD", "বিমানবন্দর থেকে কিংডম সেন্টার", "বিমানবন্দর থেকে আল বাথা", "KAFD থেকে জাতীয় জাদুঘর", "কিংডম সেন্টার থেকে সুক আল জাল", "রিয়াদ রেলস্টেশন থেকে জাতীয় জাদুঘর"],
 lines="লাইন ও স্টেশন", line="<b>{n}:</b> {a} থেকে {b}।",
 shared="ইয়েলো ও পার্পল লাইন KAFD থেকে SABIC পর্যন্ত চারটি স্টেশন ভাগ করে।",
 faq="প্রশ্ন",
 q=[("রিয়াদ মেট্রো কখন চলে?", "শনিবার থেকে বৃহস্পতিবার {wk}, শুক্রবার {fri}। রমজান ও ছুটির দিনে সময় বদলায়; রাতে দেরিতে আপনার দিকের শেষ ট্রেন বন্ধ হওয়ার আগেই ছেড়ে যেতে পারে।"),
    ("রিয়াদ মেট্রোর ভাড়া কত?", "২ ঘণ্টার টিকিট স্ট্যান্ডার্ড ক্লাসে SAR {std} এবং ফার্স্ট ক্লাসে SAR {first}, মেট্রো ও বাসে যত খুশি যাত্রা ও ট্রান্সফার। ৩, ৭ ও ৩০ দিনের পাসও আছে।"),
    ("বিমানবন্দর থেকে কি মেট্রো পাওয়া যায়?", "হ্যাঁ। ইয়েলো লাইন টার্মিনাল ১-২, ৩-৪ ও ৫ থেকে KAFD পর্যন্ত যায়, যেখানে ব্লু ও পার্পল লাইনের সঙ্গে মেলে।"),
    ("এটা কি সরকারি মানচিত্র?", "না। এটি একটি স্বাধীন, অবাণিজ্যিক প্রকল্প, রিয়াদ পাবলিক ট্রান্সপোর্টের সঙ্গে যুক্ত নয়। সময়গুলো আনুমানিক; সবসময় স্টেশনের চিহ্ন ও ঘোষণা মেনে চলুন।")],
 report="সমস্যা জানান বা উন্নতির পরামর্শ দিন", close="বন্ধ করুন", langName="বাংলা",
 guides="স্টেশন ও জায়গার গাইড (ইংরেজিতে)"),

"tl": dict(
 file="tl.html", locale="fil_PH", dir="ltr",
 title="Mapa ng Riyadh Metro at Route Planner: lahat ng 6 na linya",
 desc="Libre at hindi opisyal na mapa ng Riyadh Metro at trip planner. Papunta sa airport, KAFD, Kingdom Centre, Al Batha o National Museum nang hakbang-hakbang, may oras ng biyahe, pamasahe at oras ng operasyon, sa walong wika.",
 ogTitle="Mapa ng Riyadh Metro at Route Planner",
 ogDesc="Lahat ng anim na linya: direksyon, oras ng biyahe, pamasahe at oras ng operasyon. Libre, sa walong wika.",
 h1="Mapa ng Riyadh Metro at route planner",
 intro="Libre at hindi opisyal na mapa ng anim na linya ng Riyadh Metro. Mag-type ng lugar o istasyon, o pindutin ang istasyon sa mapa, at ipapakita ng planner ang ruta kasama ang bawat lipat, tantiyang oras ng biyahe at pamasahe. Gumagana ito sa Arabic, English, Urdu, Hindi, Bengali, Filipino, Russian at French sa phone at computer nang walang ini-install, at hinahanap ng location button ang pinakamalapit na istasyon.",
 popular="Mga sikat na biyahe",
 trips=["Airport (Terminal 1-2) papuntang KAFD", "Airport papuntang Kingdom Centre", "Airport papuntang Al Batha", "KAFD papuntang National Museum", "Kingdom Centre papuntang Souq Al Zal", "Riyadh Railway Station papuntang National Museum"],
 lines="Mga linya at istasyon", line="<b>{n}:</b> {a} hanggang {b}.",
 shared="Magkasama ang Yellow at Purple Line sa apat na istasyon mula KAFD hanggang SABIC.",
 faq="Mga tanong",
 q=[("Anong oras bukas ang Riyadh Metro?", "Sabado hanggang Huwebes {wk}, Biyernes {fri}. Nagbabago ang oras tuwing Ramadan at holiday; kapag gabi na, puwedeng umalis ang huling tren sa direksyon mo bago magsara."),
    ("Magkano ang pamasahe sa Riyadh Metro?", "Ang 2-oras na tiket ay SAR {std} sa standard class at SAR {first} sa first class, walang limitasyong sakay at lipat sa metro at bus. May 3-araw, 7-araw at 30-araw na pass din."),
    ("May metro ba mula sa airport?", "Oo. Dumadaan ang Yellow Line sa Terminal 1-2, 3-4 at 5 at papunta sa KAFD, kung saan nagtatagpo ito sa Blue at Purple Line."),
    ("Opisyal ba ang mapang ito?", "Hindi. Isa itong independiyente at hindi pangkomersyong proyekto, walang kaugnayan sa Riyadh Public Transport. Tantiya lang ang mga oras; laging sundin ang karatula at anunsyo sa istasyon.")],
 report="Mag-ulat ng problema o magmungkahi", close="Isara", langName="Filipino",
 guides="Gabay sa mga istasyon at lugar (sa English)"),
"ru": dict(
 file="ru.html", locale="ru_RU", dir="ltr",
 title="Схема метро Эр-Рияда и построение маршрута: все 6 линий",
 desc="Бесплатная неофициальная схема метро Эр-Рияда с построением маршрута. Как добраться из аэропорта до KAFD, Kingdom Centre, Аль-Батхи или Национального музея: пошаговый маршрут, время в пути, цена билета и часы работы, на 8 языках.",
 ogTitle="Схема метро Эр-Рияда и построение маршрута",
 ogDesc="Все шесть линий: как доехать, время в пути, цена билета и часы работы. Бесплатно, на 8 языках.",
 h1="Схема метро Эр-Рияда и построение маршрута",
 intro="Неофициальная бесплатная схема шести линий метро Эр-Рияда. Введите место или станцию либо нажмите на станцию на схеме, и планировщик покажет маршрут со всеми пересадками, примерным временем в пути и ценой билета. Сайт работает на арабском, английском, урду, хинди, бенгальском, филиппинском, русском и французском, на телефоне и компьютере, ничего устанавливать не нужно, а кнопка геолокации найдёт ближайшую к вам станцию.",
 popular="Популярные поездки",
 trips=["Аэропорт (терминалы 1-2) → KAFD", "Аэропорт → Kingdom Centre", "Аэропорт → Аль-Батха", "KAFD → Национальный музей", "Kingdom Centre → Souq Al Zal", "Железнодорожный вокзал Эр-Рияда → Национальный музей"],
 lines="Линии и станции", line="<b>{n}:</b> от {a} до {b}.",
 shared="Жёлтая и фиолетовая линии проходят вместе через четыре станции от KAFD до SABIC.",
 faq="Вопросы",
 q=[("Когда работает метро Эр-Рияда?", "С субботы по четверг {wk}, в пятницу {fri}. В Рамадан и праздники часы меняются; поздно вечером последний поезд в вашем направлении может уйти раньше закрытия."),
    ("Сколько стоит проезд в метро Эр-Рияда?", "Билет на 2 часа стоит {std} SAR в стандартном классе и {first} SAR в первом, на любое число поездок и пересадок в метро и автобусах. Есть также проездные на 3, 7 и 30 дней."),
    ("Можно ли доехать на метро из аэропорта?", "Да. Жёлтая линия обслуживает терминалы 1-2, 3-4 и 5 и идёт до KAFD, где пересекается с синей и фиолетовой линиями."),
    ("Это официальная схема?", "Нет. Это независимый некоммерческий проект, не связанный с транспортными властями Эр-Рияда. Время в пути примерное; на станции всегда ориентируйтесь на указатели и объявления.")],
 report="Сообщить о проблеме или предложить улучшение", close="Закрыть", langName="Русский",
 guides="Гиды по станциям и местам (на английском)"),

"fr": dict(
 file="fr.html", locale="fr_FR", dir="ltr",
 title="Plan du métro de Riyad et calcul d’itinéraire : les 6 lignes",
 desc="Plan gratuit et non officiel du métro de Riyad avec calcul d’itinéraire. De l’aéroport à KAFD, au Kingdom Centre, à Al Batha ou au Musée national : itinéraire pas à pas, temps de trajet, prix du billet et horaires, en 8 langues.",
 ogTitle="Plan du métro de Riyad et calcul d’itinéraire",
 ogDesc="Les six lignes : itinéraires, temps de trajet, prix du billet et horaires. Gratuit, en 8 langues.",
 h1="Plan du métro de Riyad et calcul d’itinéraire",
 intro="Un plan gratuit et non officiel des six lignes du métro de Riyad. Saisissez un lieu ou une station, ou touchez une station sur le plan : l’outil affiche l’itinéraire avec chaque correspondance, une estimation du temps de trajet et le prix du billet. Il fonctionne en arabe, anglais, ourdou, hindi, bengali, filipino, russe et français, sur téléphone et ordinateur, sans rien installer, et le bouton de localisation trouve la station la plus proche.",
 popular="Trajets populaires",
 trips=["Aéroport (terminaux 1-2) → KAFD", "Aéroport → Kingdom Centre", "Aéroport → Al Batha", "KAFD → Musée national", "Kingdom Centre → Souq Al Zal", "Gare de Riyad → Musée national"],
 lines="Lignes et stations", line="<b>{n} :</b> de {a} à {b}.",
 shared="Les lignes jaune et violette partagent les quatre stations de KAFD à SABIC.",
 faq="Questions",
 q=[("Quels sont les horaires du métro de Riyad ?", "Du samedi au jeudi {wk}, le vendredi {fri}. Les horaires changent pendant le Ramadan et les jours fériés ; tard le soir, le dernier train dans votre sens peut partir avant la fermeture."),
    ("Combien coûte le métro de Riyad ?", "Un billet de 2 heures coûte {std} SAR en classe standard et {first} SAR en première classe, pour autant de trajets et de correspondances que vous voulez dans le métro et les bus. Il existe aussi des forfaits 3, 7 et 30 jours."),
    ("Peut-on prendre le métro depuis l’aéroport ?", "Oui. La ligne jaune dessert les terminaux 1-2, 3-4 et 5 et va jusqu’à KAFD, où elle croise les lignes bleue et violette."),
    ("Est-ce le plan officiel ?", "Non. C’est un projet indépendant et non commercial, sans lien avec les autorités des transports de Riyad. Les temps sont estimés ; suivez toujours la signalisation et les annonces en station.")],
 report="Signaler un problème ou proposer une amélioration", close="Fermer", langName="Français",
 guides="Guides des stations et des lieux (en anglais)"),
}
ORDER = ["en", "ar", "ur", "hi", "bn", "tl", "ru", "fr"]
